[package]
name = "chip_8"
version = "0.1.0"
authors = ["Tom Goring <tgoring97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chip_8"
path = "src/main.rs"

[dependencies]
sdl2 = "0.32"
rand = "0.7"